---
title: "Leaflet Map Test"
author: "Anish Nathu"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(leaflet)
library(rgdal)
library(dplyr)
library(ggplot2)

# Reading in the shape file
# https://thematicmapping.org/downloads/world_borders.php
world_spdf <- readOGR( 
  dsn= paste0(getwd(),"/world_shape_file/") , 
  layer="TM_WORLD_BORDERS_SIMPL-0.3",
  verbose=FALSE
)


```

```{r}
# Clean the data object
world_spdf@data$POP2005[ which(world_spdf@data$POP2005 == 0)] = NA
world_spdf@data$POP2005 <- as.numeric(as.character(world_spdf@data$POP2005)) / 1000000 %>% round(2)

# -- > Now you have a Spdf object (spatial polygon data frame). You can start doing maps!
```


```{r}
WHR <- read.csv("WHR_Cleaned_Data.csv",sep=',', header = TRUE)
WHR
```

```{r}
str(WHR)
```


```{r}
# -- > Now you have a Spdf object (spatial polygon data frame). You can start doing maps!
worldCountries <- sp::merge(world_spdf, WHR, by.x="NAME", by.y="Country", all.x=TRUE, duplicateGeoms = TRUE) #all = TRUE dictates a left join from world_spdf
```


```{r}
# Create a color palette with handmade bins.
library(RColorBrewer)
mypalette <- colorBin( palette="YlOrBr", domain=worldCountries@data$Score, bins=7)
subset_data <- subset(worldCountries, worldCountries@data$Year == 2019)

# Prepare the text for tooltips:
mytext <- paste(
    "Country: ", subset_data@data$NAME,"<br/>", 
    "Region: ", subset_data@data$Region,"<br/>",
    "Happiness: ", subset_data@data$Score, "<br/>", 
    "Life_Expectancy: ", round(subset_data@data$Health, 2), "<br/>", 
    "Year: ", subset_data@data$Year,
    sep="") %>%
  lapply(htmltools::HTML)
 
# Final Map
leaflet(subset_data) %>% 
  addTiles()  %>% 
  setView( lat=10, lng=0 , zoom=2) %>%
  addPolygons( 
    fillColor = ~mypalette(Score), 
    stroke=TRUE, 
    fillOpacity = 1, 
    color="black", 
    weight=0.5,
    label = mytext,
    labelOptions = labelOptions( 
      style = list("font-weight" = "normal", padding = "3px 8px"), 
      textsize = "13px", 
      direction = "auto"
    )
  ) %>%
  addLegend( 
      values=~Score, #data in legend  
      opacity=0.9, 
      title = "World Happiness", 
      position = "bottomleft",
      colors = c("#1984c5", "#22a7f0", "#63bff0", "#a7d5ed", "#e2e2e2", "#e1a692", "#de6e56", "#e14b31", "#c23728"),
      labels = c("Less Happy", "", "", "", "", "", "", "", "More Happy"),
    )
```


```{r}

```

